name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Run tests
      run: pytest tests/ --cov=core --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v3

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to production
      run: |
        ssh user@server 'cd /opt/hydro && git pull'
        ssh user@server 'systemctl restart hydro-monitoring'